import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'surface': '#f8f9ff',
        'surface-tint': '#0053db',
        'primary-fixed': '#dbe1ff',
        'error': '#ba1a1a',
        'secondary-fixed': '#ffdbd0',
        'tertiary-fixed': '#95f8a7',
        'on-primary-container': '#eeefff',
        'primary-container': '#2563eb',
        'on-background': '#0b1c30',
        'inverse-surface': '#213145',
        'surface-container': '#e5eeff',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#117e3b',
        'on-primary': '#ffffff',
        'secondary-container': '#fd6b36',
        'on-tertiary-fixed': '#00210a',
        'on-secondary-fixed-variant': '#832600',
        'surface-container-highest': '#d3e4fe',
        'background': '#f8f9ff',
        'on-primary-fixed': '#00174b',
        'on-tertiary-fixed-variant': '#005323',
        'on-error-container': '#93000a',
        'outline': '#737686',
        'outline-variant': '#c3c6d7',
        'surface-dim': '#cbdbf5',
        'on-tertiary-container': '#c4ffc9',
        'on-surface': '#0b1c30',
        'primary-fixed-dim': '#b4c5ff',
        'on-secondary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed-dim': '#ffb59d',
        'on-secondary-fixed': '#390c00',
        'surface-bright': '#f8f9ff',
        'primary': '#004ac6',
        'tertiary': '#00632b',
        'surface-variant': '#d3e4fe',
        'secondary': '#ac3400',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#79db8d',
        'on-secondary-container': '#5d1900',
        'on-surface-variant': '#434655',
      },
      borderRadius: {
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '24px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        '2xl': '64px',
      },
      fontFamily: {
        'label-sm': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/line-clamp'),
  ],
};

export default config;
