/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f8f9ff',
        'primary': '#004ac6',
        'secondary': '#ac3400',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#434655',
        'outline': '#737686',
        'outline-variant': '#c3c6d7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed': '#00174b',
        'secondary-container': '#fd6b36',
        'on-secondary-container': '#5d1900',
        'secondary-fixed': '#ffdbd0',
        'on-secondary-fixed': '#390c00',
        'tertiary': '#00632b',
        'tertiary-container': '#117e3b',
        'on-tertiary-container': '#c4ffc9',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        'label-sm': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
